In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
def buildEqualDepthHist(data,nbin=100):
    bins = np.quantile(data, np.linspace(0,1,nbin+1))
    bin_size = len(data)/nbin
    return bins,bin_size

In [4]:
len(year)

9406943

In [5]:
# def computeSingleSidedSelectivity(bins,bin_size,X):
#     for l in range(len(bins)):
#         if(bins[l]>X):
#             break
#     if(l==0):
#         return 0
#     else:
#         return (X-bin[l-1])/(bin[l]-bin[l-1])*bin_size + (l-1)*bin_size

In [18]:
def computeRangeCardinality(bins,bin_size,left,right):

    if(right<bins[0] or left>bins[-1]):
        return 0

    for l in range(len(bins)):
        if(bins[l]>=left):
            break
    for r in range(len(bins)-1,-1,-1):
        if(bins[r]<=right):
            break
    # print(l,r)

    if(l==r and l==len(bins)-1):
        return(bins[l]-left)/(bins[l]-bins[l-1])*bin_size
    elif(l==r and l==0):
        return(right-bins[l])/(bins[l+1]-bins[l])*bin_size
    elif(l==r):
        return ((bins[l]-left)/(bins[l]-bins[l-1]) + (right-bins[r])/(bins[r+1]-bins[r]))*bin_size
    elif(l==0 and r==len(bins)-1):
        return bin_size * (len(bins)-1)
    elif(l==0):
        return (r-l + (right-bins[r])/(bins[r+1]-bins[r]))*bin_size
    elif(r==len(bins)-1):
        return (r-l + (bins[l]-left)/(bins[l]-bins[l-1]))*bin_size
    else:
        return (r-l + (bins[l]-left)/(bins[l]-bins[l-1]) + (right-bins[r])/(bins[r+1]-bins[r]))*bin_size


In [29]:
bins, bin_size = buildEqualDepthHist(year,5)
computeRangeCardinality(bins,bin_size,1900,2010)/9406943

0 2


0.4

In [29]:
bins

array([1900., 2005., 2010., 2014., 2017., 2020.])

In [ ]:
9406943

In [31]:
raw_data = pd.read_csv("/data/sunluming/datasets/cover.csv").to_numpy()
bins = []
bin_size = []
n_distinct = [1978, 361, 67, 551, 700, 5785, 207, 185, 255, 5827]
pwl_calibration_num_keypoints = (np.array(n_distinct)**0.5).astype(int)
for i in range(len(n_distinct)):
    b,bs = buildEqualDepthHist(raw_data[:,i],nbin=pwl_calibration_num_keypoints[i]-1)
    bins.append(b)
    bin_size.append(bs)
for each in bins:
    for i in range(len(each)-1):
        if(each[i]==each[i+1]):
            each[i+1] += 1

In [32]:
pwl_calibration_num_keypoints

array([44, 19,  8, 23, 26, 76, 14, 13, 15, 76])

In [33]:
pwl_calibration_num_keypoints = (np.minimum(np.array(n_distinct)*0.4,500*0.1)).astype(int)

In [34]:
pwl_calibration_num_keypoints

array([50, 50, 26, 50, 50, 50, 50, 50, 50, 50])

In [35]:
bins

[array([1859., 2257., 2390., 2496., 2564., 2614., 2661., 2701., 2733.,
        2762., 2789., 2815., 2840., 2862., 2883., 2902., 2919., 2935.,
        2949., 2962., 2975., 2989., 3003., 3017., 3031., 3046., 3062.,
        3078., 3094., 3111., 3127., 3143., 3159., 3175., 3191., 3207.,
        3223., 3240., 3258., 3279., 3304., 3343., 3391., 3858.]),
 array([  0.,  13.,  27.,  39.,  52.,  65.,  78.,  93., 109., 127., 148.,
        175., 205., 242., 277., 305., 325., 342., 360.]),
 array([ 0.,  6.,  9., 12., 14., 17., 22., 66.]),
 array([   0.,   30.,   31.,   60.,   67.,   90.,  120.,  134.,  153.,
         180.,  201.,  218.,  247.,  272.,  300.,  331.,  362.,  404.,
         450.,  510.,  577.,  700., 1397.]),
 array([-173.,  -11.,   -2.,    0.,    1.,    3.,    6.,    9.,   12.,
          16.,   19.,   23.,   27.,   32.,   37.,   42.,   48.,   55.,
          62.,   71.,   81.,   94.,  111.,  135.,  178.,  601.]),
 array([   0. ,  175. ,  256. ,  330. ,  391. ,  451. ,  510. ,  564. ,
 